spring.application.name=YoutubeTools
youtube.api.key=YOUR YOUTUBE API KEY
youtube.api.base.url=https://www.googleapis.com/youtube/v3
youtube.api.search.url=https://www.googleapis.com/youtube/v3/search
youtube.api.video.url=https://www.googleapis.com/youtube/v3/videos

#maximum number of related videos to be fetched from youtube api
youtube.api.max.related.videos=15
